name: Deploy

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set-up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache
          key: dependencies-v1-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Cache Docker images
        uses: ScribeMD/docker-cache@0.3.6
        with:
          key: docker-v1-${{ runner.os }}-${{ hashFiles('package.json') }}
      - name: Publish
        run: |
          yarn install --frozen-lockfile
          npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configurationJson: |
            {
              "categories": [
                {
                  "title": "## 🚀 Features",
                  "labels": ["feature", "enhancement", "request"]
                },
                {
                  "title": "## 🛠 Fixes",
                  "labels": ["fix", "bug"]
                },
                {
                  "title": "## 🧩 Dependencies",
                  "labels": ["dependencies"]
                },
                {
                  "title": "## ⚙️ Configuration",
                  "labels": ["configuration"]
                },
                {
                  "title": "## 🧪 Tests",
                  "labels": ["tests"]
                },
                {
                  "title": "## 📦 Other",
                  "labels": []
                }
              ],
              "template": "#{{CHANGELOG}}",
              "pr_template": "- #{{TITLE}}\n   - PR: ##{{NUMBER}} by @#{{AUTHOR}}",
              "empty_template": "#{{OWNER}}\n#{{REPO}}\n#{{FROM_TAG}}\n#{{TO_TAG}}",
              "max_pull_requests": 1000,
              "max_back_track_time_days": 1000,
              "label_extractor": [
                {
                  "pattern": "^fix",
                  "on_property": "title",
                  "method": "match",
                  "flags": "i"
                }
              ]
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/index.js
            dist/index.d.ts
          body: |
            ${{ steps.build_changelog.outputs.changelog }}